language: objective-c
rvm: 2.3
# https://docs.travis-ci.com/user/reference/osx
osx_image: xcode10.1
env:
  global:
    - IOS_SIMULATOR="iPhone 6s"
    - IOS_VERSION="12.1"
matrix:
  include:
    - env: BUILD_SCHEME="SQLite iOS"
    - env: BUILD_SCHEME="SQLite Mac"
    - env: VALIDATOR_SUBSPEC="none"
    - env: VALIDATOR_SUBSPEC="standard"
    - env: VALIDATOR_SUBSPEC="standalone"
    - env: VALIDATOR_SUBSPEC="SQLCipher"
    - env: CARTHAGE_PLATFORM="iOS"
    - env: CARTHAGE_PLATFORM="Mac"
    - env: CARTHAGE_PLATFORM="watchOS"
    - env: CARTHAGE_PLATFORM="tvOS"
    - env: PACKAGE_MANAGER_COMMAND="test"
before_install:
  - gem update bundler
  - gem install xcpretty --no-document
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - ./run-tests.sh
