language: objective-c
rvm: 2.2
osx_image: xcode8.2
env:
  global:
    - IOS_SIMULATOR="iPhone 6s"
matrix:
  include:
    - env: BUILD_SCHEME="SQLite iOS"
    - env: BUILD_SCHEME="SQLite Mac"
    - env: VALIDATOR_SUBSPEC="none"
    - env: VALIDATOR_SUBSPEC="standard"
    - env: VALIDATOR_SUBSPEC="standalone"
    - env: VALIDATOR_SUBSPEC="SQLCipher"
before_install:
  - gem update bundler
  - gem install xcpretty --no-document
script:
  - ./run-tests.sh
